spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 20
        max-page-size: 2000

  datasource:
    url: jdbc:h2:~/soccer:AUTO_SERVER=true
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100


soccer:
  jwt-key: "bCpkCjHuWStC+JS5YJVB62L86r7Wenb/EFHs2q5xgjE="


